/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#bdc2ff",
        "surface-dim": "#11131c",
        "primary-fixed": "#e0e0ff",
        "on-tertiary-fixed-variant": "#7b008f",
        "on-surface-variant": "#c6c5d4",
        "tertiary-fixed-dim": "#f9abff",
        "on-secondary-fixed-variant": "#00497d",
        "on-primary-fixed": "#000767",
        "surface-container-lowest": "#0c0e17",
        "error-container": "#93000a",
        tertiary: "#f9abff",
        "on-secondary": "#003258",
        "surface-container-high": "#282933",
        "surface-container": "#1d1f29",
        "on-secondary-fixed": "#001d36",
        "secondary-fixed-dim": "#9ecaff",
        "tertiary-fixed": "#ffd6fe",
        "on-tertiary-container": "#dd67ee",
        surface: "#11131c",
        "on-background": "#e1e1ef",
        "on-secondary-container": "#002b4d",
        "on-error": "#690005",
        "surface-container-low": "#191b24",
        "surface-container-highest": "#32343e",
        "inverse-primary": "#4c56af",
        "on-surface": "#e1e1ef",
        "outline-variant": "#454652",
        "secondary-fixed": "#d1e4ff",
        "on-tertiary": "#570066",
        "tertiary-container": "#560065",
        "primary-fixed-dim": "#bdc2ff",
        "on-primary-fixed-variant": "#343d96",
        "inverse-surface": "#e1e1ef",
        error: "#ffb4ab",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#35003f",
        "on-primary": "#1b247f",
        "on-primary-container": "#8690ee",
        "primary-container": "#1a237e",
        "surface-variant": "#32343e",
        "secondary-container": "#1e95f2",
        "inverse-on-surface": "#2e303a",
        background: "#11131c",
        secondary: "#9ecaff",
        outline: "#908f9d",
        "surface-bright": "#373943",
        primary: "#bdc2ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "40px",
        base: "4px",
        sm: "16px",
        xs: "8px",
        md: "24px",
        gutter: "20px",
        xl: "64px",
        margin: "32px",
      },
      fontFamily: {
        "data-mono": ["Inter"],
        "body-base": ["Inter"],
        "display-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "data-mono": ["14px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-base": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
